### ISSUE TITLE
Error in parsing cloudformation templates

### ISSUE THREAD

**Issue by SvenMarquardt5772** [awslabs/aws-cloudformation-iam-policy-validator#3]
I have multiple valid cloudformation templates, that the validator cannot parse.

`❯ cfn-lint -t cdk.out/jenkins-build-role-image-builder.template.json `

`❯ cfn-policy-validator validate --template-path cdk.out/jenkins-build-role-image-builder.template.json --region eu-central-1 2> error.log`

Attached is the error log.
[error.log](https://github.com/awslabs/aws-cloudformation-iam-policy-validator/files/7257826/error.log)

**Comment by SvenMarquardt5772** [comment]
It seems the join is an issue there.

**Comment by mluttrell** [comment]
Are you able to provide a snippet of the join that's failing?  Or if it's easier, you can send the whole template to matluttr@amazon.com

**Comment by mluttrell** [comment]
I was able to reproduce and just released a fix.  Try grabbing the latest from PyPI and please reopen the issue if you're still having problems.

The explanation - I use jsonschema to validate your template's schema in order to provide better error messages when something goes wrong.  I specified a version range for jsonschema that was too wide and a new major version was released ~12 hours ago that included a breaking change to how this tool validates schemas.

**Comment by SvenMarquardt5772** [comment]
Yes, this is now fixed for me as of 0.0.4. Thanks for the quick fix.
